"""dequantize_u8 — generated by ea bind"""
import ctypes as _ct
import numpy as _np
from pathlib import Path as _Path

_lib = _ct.CDLL(str(_Path(__file__).parent / "lib" / "libdequantize_u8.so"))

_lib.q4_dequantize_u8_f32.argtypes = [_ct.POINTER(_ct.c_uint8), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.c_int32]
_lib.q4_dequantize_u8_f32.restype = None

def q4_dequantize_u8_f32(weights: _np.ndarray, scales: _np.ndarray, biases: _np.ndarray, out: _np.ndarray, n_groups: int):
    """q4_dequantize_u8_f32(weights: *restrict u8, scales: *restrict f32, biases: *restrict f32, out: *mut f32, n_groups: i32) -> void"""
    if weights.dtype != _np.uint8:
        raise TypeError("weights: expected uint8")
    if scales.dtype != _np.float32:
        raise TypeError("scales: expected float32")
    if biases.dtype != _np.float32:
        raise TypeError("biases: expected float32")
    if out.dtype != _np.float32:
        raise TypeError("out: expected float32")
    _lib.q4_dequantize_u8_f32(
        weights.ctypes.data_as(_ct.POINTER(_ct.c_uint8)),
        scales.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        biases.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        out.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        _ct.c_int32(int(n_groups))
    )

_lib.q4_dequantize_range_u8_f32.argtypes = [_ct.POINTER(_ct.c_uint8), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.c_int32, _ct.c_int32]
_lib.q4_dequantize_range_u8_f32.restype = None

def q4_dequantize_range_u8_f32(weights: _np.ndarray, scales: _np.ndarray, biases: _np.ndarray, out: _np.ndarray, group_start: int, group_count: int):
    """q4_dequantize_range_u8_f32(weights: *restrict u8, scales: *restrict f32, biases: *restrict f32, out: *mut f32, group_start: i32, group_count: i32) -> void"""
    if weights.dtype != _np.uint8:
        raise TypeError("weights: expected uint8")
    if scales.dtype != _np.float32:
        raise TypeError("scales: expected float32")
    if biases.dtype != _np.float32:
        raise TypeError("biases: expected float32")
    if out.dtype != _np.float32:
        raise TypeError("out: expected float32")
    _lib.q4_dequantize_range_u8_f32(
        weights.ctypes.data_as(_ct.POINTER(_ct.c_uint8)),
        scales.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        biases.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        out.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        _ct.c_int32(int(group_start)),
        _ct.c_int32(int(group_count))
    )

