"""quantize — generated by ea bind"""
import ctypes as _ct
import numpy as _np
from pathlib import Path as _Path

_lib = _ct.CDLL(str(_Path(__file__).parent / "lib" / "libquantize.so"))

_lib.q4_quantize_f32.argtypes = [_ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_int32), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.c_int32]
_lib.q4_quantize_f32.restype = None

def q4_quantize_f32(src: _np.ndarray, weights_out: _np.ndarray, scales_out: _np.ndarray, biases_out: _np.ndarray, n_groups: int):
    """q4_quantize_f32(src: *restrict f32, weights_out: *mut i32, scales_out: *mut f32, biases_out: *mut f32, n_groups: i32) -> void"""
    if src.dtype != _np.float32:
        raise TypeError("src: expected float32")
    if weights_out.dtype != _np.int32:
        raise TypeError("weights_out: expected int32")
    if scales_out.dtype != _np.float32:
        raise TypeError("scales_out: expected float32")
    if biases_out.dtype != _np.float32:
        raise TypeError("biases_out: expected float32")
    _lib.q4_quantize_f32(
        src.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        weights_out.ctypes.data_as(_ct.POINTER(_ct.c_int32)),
        scales_out.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        biases_out.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        _ct.c_int32(int(n_groups))
    )

_lib.q4_quantize_validated_f32.argtypes = [_ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_int32), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.c_int32]
_lib.q4_quantize_validated_f32.restype = _ct.c_int32

def q4_quantize_validated_f32(src: _np.ndarray, weights_out: _np.ndarray, scales_out: _np.ndarray, biases_out: _np.ndarray, n_groups: int) -> int:
    """q4_quantize_validated_f32(src: *restrict f32, weights_out: *mut i32, scales_out: *mut f32, biases_out: *mut f32, n_groups: i32) -> i32"""
    if src.dtype != _np.float32:
        raise TypeError("src: expected float32")
    if weights_out.dtype != _np.int32:
        raise TypeError("weights_out: expected int32")
    if scales_out.dtype != _np.float32:
        raise TypeError("scales_out: expected float32")
    if biases_out.dtype != _np.float32:
        raise TypeError("biases_out: expected float32")
    _result = _lib.q4_quantize_validated_f32(
        src.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        weights_out.ctypes.data_as(_ct.POINTER(_ct.c_int32)),
        scales_out.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        biases_out.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        _ct.c_int32(int(n_groups))
    )
    return int(_result)

