"""validate — generated by ea bind, with wrapper for ergonomic NaN detection."""
import ctypes as _ct
import numpy as _np
from pathlib import Path as _Path

_lib = _ct.CDLL(str(_Path(__file__).parent / "lib" / "libvalidate.so"))

_lib.q4_validate.argtypes = [_ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_float), _ct.POINTER(_ct.c_int32), _ct.POINTER(_ct.c_int32), _ct.c_int32]
_lib.q4_validate.restype = _ct.c_int32

def _q4_validate_raw(scales: _np.ndarray, biases: _np.ndarray, scales_bits: _np.ndarray, biases_bits: _np.ndarray, n_groups: int) -> int:
    """Raw kernel call — requires both f32 and i32 views."""
    if scales.dtype != _np.float32:
        raise TypeError("scales: expected float32")
    if biases.dtype != _np.float32:
        raise TypeError("biases: expected float32")
    if scales_bits.dtype != _np.int32:
        raise TypeError("scales_bits: expected int32")
    if biases_bits.dtype != _np.int32:
        raise TypeError("biases_bits: expected int32")
    _result = _lib.q4_validate(
        scales.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        biases.ctypes.data_as(_ct.POINTER(_ct.c_float)),
        scales_bits.ctypes.data_as(_ct.POINTER(_ct.c_int32)),
        biases_bits.ctypes.data_as(_ct.POINTER(_ct.c_int32)),
        _ct.c_int32(int(n_groups))
    )
    return int(_result)


def q4_validate(scales: _np.ndarray, biases: _np.ndarray, n_groups: int) -> int:
    """Validate Q4 quantized data. Returns 0 if ok, error code if corrupt.

    Error codes: 1=NaN scale, 2=NaN bias, 3=negative scale.
    """
    if scales.dtype != _np.float32:
        raise TypeError("scales: expected float32")
    if biases.dtype != _np.float32:
        raise TypeError("biases: expected float32")
    scales_bits = scales.view(_np.int32)
    biases_bits = biases.view(_np.int32)
    return _q4_validate_raw(scales, biases, scales_bits, biases_bits, n_groups)
